<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body"> 
                 <?php echo (isset($this->alert) ? $this->alert : ''); ?>           
            <form action="<?php echo BASE; ?>recuperar/solicitar/" class="form-horizontal" method="post">
                  <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">E-mail</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" name="email" id="email" placeholder="seuemail@dominio.com">
                    </div>
                  </div>                  
                  <div class="form-group">                    
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-success">Enviar Link de Recuperação</button>
                    </div>
                  </div>
            </form>
            </div>
        </div>
    </div>
</div>
